id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py::test_case_0,functional_correctness_test_folder.csn.gpt-5.partial_docstr.test_snippet_291,test_case_0,functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py,,,passed,,8.349999552592635e-05
functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py::test_case_1,functional_correctness_test_folder.csn.gpt-5.partial_docstr.test_snippet_291,test_case_1,functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py,,,passed,,7.112501771189272e-05
functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py::test_case_2,functional_correctness_test_folder.csn.gpt-5.partial_docstr.test_snippet_291,test_case_2,functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py,,xfail,failed,[XPASS(strict)] ,6.366599700413644e-05
functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py::test_case_3,functional_correctness_test_folder.csn.gpt-5.partial_docstr.test_snippet_291,test_case_3,functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py,,,failed,Failed: DID NOT RAISE <class 'TimeoutError'>,0.00010149998706765473
functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py::test_case_4,functional_correctness_test_folder.csn.gpt-5.partial_docstr.test_snippet_291,test_case_4,functional_correctness_test_folder/csn/gpt-5/partial_docstr/test_snippet_291.py,,xfail,xfailed,,8.329199044965208e-05
