id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/csn/gpt-4.1/partial_docstr/test_snippet_264.py::test_case_0,functional_correctness_test_folder.csn.gpt-4.1.partial_docstr.test_snippet_264,test_case_0,functional_correctness_test_folder/csn/gpt-4.1/partial_docstr/test_snippet_264.py,,,failed,AttributeError: type object 'Plot_Data' has no attribute 'count',9.129202226176858e-05
