id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py::test_case_0,functional_correctness_test_folder.post_cut-off.gpt-4.1.partial_docstr.test_snippet_281,test_case_0,functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py,,,failed,Failed: DID NOT RAISE <class 'ValueError'>,0.0004483319935388863
functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py::test_case_1,functional_correctness_test_folder.post_cut-off.gpt-4.1.partial_docstr.test_snippet_281,test_case_1,functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py,,,failed,TypeError: 'NoneType' object is not iterable,0.0002606020134408027
functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py::test_case_2,functional_correctness_test_folder.post_cut-off.gpt-4.1.partial_docstr.test_snippet_281,test_case_2,functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py,,,failed,assert True is False,0.00039475501398555934
functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py::test_case_3,functional_correctness_test_folder.post_cut-off.gpt-4.1.partial_docstr.test_snippet_281,test_case_3,functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py,,,failed,assert True is False,0.0003659290086943656
functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py::test_case_4,functional_correctness_test_folder.post_cut-off.gpt-4.1.partial_docstr.test_snippet_281,test_case_4,functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py,,xfail,failed,[XPASS(strict)] ,0.00022955500753596425
functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py::test_case_5,functional_correctness_test_folder.post_cut-off.gpt-4.1.partial_docstr.test_snippet_281,test_case_5,functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py,,,failed,AttributeError: 'str' object has no attribute 'items',0.000293057004455477
functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py::test_case_6,functional_correctness_test_folder.post_cut-off.gpt-4.1.partial_docstr.test_snippet_281,test_case_6,functional_correctness_test_folder/post_cut-off/gpt-4.1/partial_docstr/test_snippet_281.py,,xfail,xfailed,,0.00024360697716474533
